language: go

go:
    - 1.x
    - tip

matrix:
    allow_failures:
        - go: tip

install:
    - go get -t ./...
    - go get github.com/FiloSottile/vendorcheck

script:
    - vendorcheck ./...
    - go test -v ./...